/*

Copyright (c) 2014 Yichi Zhang
https://github.com/yichizhang
zhang-yi-chi@hotmail.com

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

*/

import Cocoa

let HASH_STRING = "#"
let EXCLAMATION_MARK_STRING = "!"
let EXCLAMATION_MARK_CHAR = Character(EXCLAMATION_MARK_STRING)
let DOUBLE_QUOTE_STRING = "\""
let DOUBLE_QUOTE_CHAR = Character(DOUBLE_QUOTE_STRING)
let SPACE_STRING = " "
let NEW_LINE_STRING = "\n"
let NEW_LINE_CHAR = Character(NEW_LINE_STRING)
let FONT_SUFFIX = "Font"
let COLOR_SUFFIX = "Color"
let COMMENT_PREFIX = "//"

let SINGLE_LINE_COMMENT = "//"
let MULTI_LINE_COMMENT_START = "/*"
let MULTI_LINE_COMMENT_END = "*/"

let paramKey_exportTo = "exportTo"
let paramKey_classFuncPrefix = "classFuncPrefix"
let paramKey_ = ""

let fileKey_mainSource = "mainSource"
let fileKey_ = ""

let Settings = SettingsManager.sharedInstance

enum Platform : Int {
	case iOS = 0
	case MacOS
}

protocol BaseModelProtocol {
	
	func autoMethodName() -> String
	func statementString() -> String
    func documentationString() -> String
	func funcString() -> String
}

class BaseModel : NSObject {
	
	var identifier = "someIdentifier"

}

enum ArgumentFormattingStrategy : Int {
	case CGFloatNumber = 0
	case StringLiteral
	case Name
}

class Argument : NSObject {
	var object:AnyObject!
	var formattingStrategy:ArgumentFormattingStrategy!
	
	init(object:AnyObject, formattingStrategy:ArgumentFormattingStrategy) {
		self.object = object
		self.formattingStrategy = formattingStrategy
		super.init()
	}
	
	var formattedString:String {
		switch formattingStrategy.rawValue {
		case ArgumentFormattingStrategy.CGFloatNumber.rawValue:
			return NSString(format: "%.3f", object.floatValue) as String
		case ArgumentFormattingStrategy.StringLiteral.rawValue:
			let str = object as! String
			return "\"" + str + "\""
		case ArgumentFormattingStrategy.Name.rawValue:
			return "\(object)"
//			return object as String
		default:
			return "__ERROR__"
		}
	}
}

class SettingsManager : NSObject {
	
	var platform : Platform {
		didSet {
			updateStrings()
		}
	}
	
	var colorClassName:String!
//	var colorRGBAInitMethodFormatString:String!
	var colorRGBAInitSignatureString:String!
	
	var fontClassName:String!
//	var fontNameAndSizeInitMethodFormatString:String!
//	var fontOfSizeInitMethodFormatString:String!
	var fontNameAndSizeInitSignatureString:String!
	
	var parameters:[String: String] = Dictionary()
	
	var userName:String {
		return "User"
	}
	var companyName:String {
		return "The Lazy Cocoa Project"
	}
	var fileName:String {
		if let exportPath = self.parameterForKey(paramKey_exportTo) {
			return exportPath.lastPathComponent
		} else {
			return ""
		}
	}
	var messageString:String {
		return "Generated by Lazy Cocoa"
	}
	
	var headerComment:String {
		return NSString(format:
			"//  \n//  %@ \n//  %@ \n// \n//  Created by %@ on 6/02/2015. \n//  Copyright (c) 2015 %@. All rights reserved. \n// \n\n\n",
			fileName,
			messageString,
			userName,
			companyName
		) as! String
	}
	
	var currentDocumentRealPath : String? {
		didSet{
			
		}
	}
	
	class var sharedInstance : SettingsManager {
		struct _SettingsStruct {
			static let instance = SettingsManager()
		}
		return _SettingsStruct.instance
	}
	
	override init() {
		platform = .iOS
		super.init()
		updateStrings()
	}
	
	func updateStrings() {

		switch platform {
		case .iOS:
			fontClassName = "UIFont"
			colorClassName = "UIColor"
			
//			colorRGBAInitMethodFormatString = colorClassName + "(red:%.3f, green:%.3f, blue:%.3f, alpha:%.3f)"
			colorRGBAInitSignatureString = "red:green:blue:alpha:"
			
		case .MacOS:
			fontClassName = "NSFont"
			colorClassName = "NSColor"
			
//			colorRGBAInitMethodFormatString = colorClassName + "(calibratedRed:%.3f, green:%.3f, blue:%.3f, alpha:%.3f)"
			colorRGBAInitSignatureString = "calibratedRed:green:blue:alpha:"
			
		}
		
//		fontOfSizeInitMethodFormatString = fontClassName + "(name:\"%@\", size:size)"
//		fontNameAndSizeInitMethodFormatString = fontClassName + "(name:\"%@\", size:%.1f)"
		
		fontNameAndSizeInitSignatureString = "name:size:"
	}
	
	func settingsChanged() {
		
	}
	
	func setParameter(#value:String, forKey parameterKey:String) {
		parameters[parameterKey] = value
	}
	
	func parameterForKey(key:String) -> String? {
		return parameters[key]
	}
	
	func unwrappedParameterForKey(key:String) -> String {
		if let val = parameterForKey(key) {
			return val
		} else {
			return ""
		}
	}
	
}

extension String {
	var isValidNumber:Bool {
		var setOfNonNumberCharacters = NSCharacterSet.decimalDigitCharacterSet().invertedSet.mutableCopy() as! NSMutableCharacterSet
		setOfNonNumberCharacters.removeCharactersInString(".")
		
		if( self.containsCharactersInSet(setOfNonNumberCharacters) ){
			return false
		}
		return true
		
	}
	func containsCharactersInSet(set:NSCharacterSet) -> Bool {
		
		// FIXME: Use Swift native String
		let range = (self as NSString).rangeOfCharacterFromSet(set)
		if(range.location == NSNotFound){
			// Does not contain characters in set
			return false
		}
		return true
		
	}
	var isValidColorCode:Bool {
		
		return hasPrefix(HASH_STRING)
	}
	var isMeantToBeComment:Bool {
		
		return hasPrefix(COMMENT_PREFIX)
	}
	var isMeantToBeFont:Bool {
		
		return hasSuffix(FONT_SUFFIX)
	}
	var isMeantToBeColor:Bool {
		
		return hasSuffix(COLOR_SUFFIX)
	}
	var isMeantToBeNeitherFontOrColor:Bool {
		
		return !(isMeantToBeFont && isMeantToBeColor)
	}
	
	static func importStatementString(string:String) -> String {
		return "import " + string + "\n"
	}
	
	static func initString(#className:String, initMethodSignature:String, arguments:[Any?] ) -> String {
		// FIXME: ---
		var args:[Argument] = Array()
		
		for (i, n) in enumerate(arguments) {
			if let float = n as? Float {
				args.append( Argument(object: CGFloat(float), formattingStrategy: .CGFloatNumber) )
			} else if let float = n as? CGFloat {
				args.append( Argument(object: CGFloat(float), formattingStrategy: .CGFloatNumber) )
			} else if let str = n as? String {
				args.append( Argument(object: str, formattingStrategy: .Name) )
			} else if let a = n as? Argument {
				args.append( a )
			} else {
				args.append( Argument(object: "__ERROR__", formattingStrategy: .Name) )
			}
		}
		
		var string = "\(className)("
		
		let m = initMethodSignature.componentsSeparatedByString(":")
	
		for (i, n) in enumerate(m) {
			if i < args.count {
				string = string + n + ":" + args[i].formattedString
			}
			if i < args.count - 1 {
				string = string + ", "
			}
		}
		
		string = string + ")"
		
		return string
	}
	
    static func methodString(#methodSignature:String, parameters:[AnyObject], returnType:String, statements:String ) -> String {
		var string = ""
		return string
	}
	
	func characterAtIndex(index:Int) -> Character{
		
		return Array(self)[index]
	}
	
	var length:Int{
		
		return count(self)
	}
	
	func safeSubstring(#start:Int, length len:Int) -> String {
		//WORKS
		let nsstring = self as NSString
		let maxLength = min( len, nsstring.length - start )
		return (nsstring.substringWithRange(NSMakeRange(start, maxLength) ) as String)
		
		//DOES NOT WORK
//		let range = Range(start: advance(self.startIndex, start),
//			end: advance(self.startIndex, start + min(length, count(self) - start) )
//			)
//		return self.substringWithRange(range)

//		
//		return self.substringWithRange(Range<String.Index>(start: advance(self.startIndex, startIndex), end: advance(self.startIndex, startIndex + min(length, count(self) - startIndex ) ) ) )
	}
	
	func stringByIndenting(#numberOfTabs:Int) -> String {
		
		let array = self.componentsSeparatedByString("\n")
		let newArray = array.map({ (string) -> String in
			var newString = ""
			for _ in 0..<numberOfTabs {
					newString += "\t"
			}
			newString += string
			
			return newString
		})
		
		return "\n".join(newArray)
	}
	
    func stringInSwiftDocumentationStyle() -> String {
        return "/** \n" + self.stringByIndenting(numberOfTabs:1) + "\n*/\n"
    }
	
	func stringByTrimmingWhiteSpaceAndNewLineCharacters() -> String {
		return self.stringByTrimmingCharactersInSet(NSCharacterSet.whitespaceAndNewlineCharacterSet())
	}
}